### ISSUE TITLE
体验

### ISSUE THREAD

**Issue by FrogGuaGua** [duanyukai/DDWuxiaHelper#1]
新发模拟器做的很用心了，但是这个UI有点反人类

**Comment by duanyukai** [comment]
第一个的确我会考虑设计一下布局，上次更新就已经改变一次结构了，还需继续优化。
第二个我有空调研一下，那个点枢机的是我自己脑补的需求，个人来说复刻出游戏的配置很快的，善用自动充穴。当然我还是考虑下大家的需求，下个月更新一下。

**Comment by 1375944297** [comment]
楼主,这些接口数据是官方提供的,还是你自己每天去爬下来的。如果是官方提供的话,可以给参考地址吗。

**Comment by duanyukai** [comment]
> 楼主,这些接口数据是官方提供的,还是你自己每天去爬下来的。如果是官方提供的话,可以给参考地址吗。

数据是我每天去爬的，官方不可能给我接口的…功力的话，是从手机助手页面抓的
