### ISSUE TITLE
要是有雅集答题器就好了

### ISSUE THREAD

**Issue by ddknight** [duanyukai/DDWuxiaHelper#2]
要是有雅集答题器就好了

**Comment by duanyukai** [comment]
雅集的题库我是有的，做到网站上一个版本非常容易，我有空随手弄一个。如果你说的是类似集成到游戏中的答题器的话，虽然能做，但官方不让做秒答功能的。

**Comment by ddknight** [comment]
当然不是抢答的那个啦.雅集题集还是很好的,至少工具站强大就不用到处找资料了.
