### ISSUE TITLE
优化点:天涯吉凶时刻增加画集创作预告

### ISSUE THREAD

**Issue by ddknight** [duanyukai/DDWuxiaHelper#3]
画集创作一直都是要完成对应的调查任务和对应时刻和天气预告,不知道系统的天气是否有循环轨迹可循,如果有的话,时刻表加上天气表就可以确定各个地区的画集创作预告了.不知道是否可以制作.

**Comment by duanyukai** [comment]
天气系统预测研究了很久，没辙，随机种子应该是每个服务器独立的。简单的时间预告还是可以的，我可以考虑加一下。
